# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/kris/Desktop/PyQt5/form.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_firstMainWin(object):
    def setupUi(self, firstMainWin):
        firstMainWin.setObjectName("firstMainWin")
        firstMainWin.resize(800, 600)
        self.pushButton = QtWidgets.QPushButton(firstMainWin)
        self.pushButton.setGeometry(QtCore.QRect(490, 110, 93, 28))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(firstMainWin)
        QtCore.QMetaObject.connectSlotsByName(firstMainWin)

    def retranslateUi(self, firstMainWin):
        _translate = QtCore.QCoreApplication.translate
        firstMainWin.setWindowTitle(_translate("firstMainWin", "firstMainWin"))
        self.pushButton.setText(_translate("firstMainWin", "PushButton"))
